/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignments;
import dashboard.dashboard;
import java.awt.Color;
import javax.swing.JOptionPane;
import learning_management_system.login.loginApllication;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.awt.Desktop;
import Cources.cources;
import Cources.cources2;
import Cources.cources3;
import Time_table.ttable;


/**
 *
 * @author Marwan
 */
public class assignments_app2 extends javax.swing.JFrame {

    /**
     * Creates new form assignments_app
     */
    public assignments_app2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Panel_redondo.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        Home_btn = new javax.swing.JButton();
        cources = new javax.swing.JButton();
        Assignments_btn = new javax.swing.JButton();
        TTable = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        English_btn = new javax.swing.JButton();
        IT_btn = new javax.swing.JButton();
        HND_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        upload_btn = new javax.swing.JButton();
        upload_btn1 = new javax.swing.JButton();
        upload_btn2 = new javax.swing.JButton();
        upload_btn3 = new javax.swing.JButton();
        upload_btn4 = new javax.swing.JButton();
        upload_btn5 = new javax.swing.JButton();
        open_btn4 = new javax.swing.JButton();
        open_btn5 = new javax.swing.JButton();
        Delete_btn5 = new javax.swing.JButton();
        Delete_btn4 = new javax.swing.JButton();
        Delete_btn3 = new javax.swing.JButton();
        Delete_btn2 = new javax.swing.JButton();
        Delete_btn1 = new javax.swing.JButton();
        open_btn1 = new javax.swing.JButton();
        open_btn2 = new javax.swing.JButton();
        open_btn3 = new javax.swing.JButton();
        open_btn = new javax.swing.JButton();
        Delete_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(232, 241, 242));

        panelRound1.setBackground(new java.awt.Color(0, 23, 61));
        panelRound1.setForeground(new java.awt.Color(0, 23, 61));
        panelRound1.setPreferredSize(new java.awt.Dimension(258, 737));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/logo1.png"))); // NOI18N

        Home_btn.setBackground(new java.awt.Color(194, 232, 248));
        Home_btn.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        Home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/home 1.png"))); // NOI18N
        Home_btn.setText(" Home         ");
        Home_btn.setPreferredSize(new java.awt.Dimension(324, 69));
        Home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_btnActionPerformed(evt);
            }
        });

        cources.setBackground(new java.awt.Color(194, 232, 248));
        cources.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        cources.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/online-learning 1.png"))); // NOI18N
        cources.setText("My Cources");
        cources.setPreferredSize(new java.awt.Dimension(324, 69));
        cources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courcesActionPerformed(evt);
            }
        });

        Assignments_btn.setBackground(new java.awt.Color(194, 232, 248));
        Assignments_btn.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        Assignments_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/paper 2.png"))); // NOI18N
        Assignments_btn.setText("Assignments");
        Assignments_btn.setPreferredSize(new java.awt.Dimension(324, 69));
        Assignments_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assignments_btnActionPerformed(evt);
            }
        });

        TTable.setBackground(new java.awt.Color(194, 232, 248));
        TTable.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        TTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/schedule 1.png"))); // NOI18N
        TTable.setText(" Time Table  ");
        TTable.setPreferredSize(new java.awt.Dimension(324, 69));
        TTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTableActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/profile 1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hi, Marwan");

        exitButton.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/remove-button1.png"))); // NOI18N
        exitButton.setText("Exit        ");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/logout1.png"))); // NOI18N
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cources, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Assignments_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(TTable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addComponent(Home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cources, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Assignments_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TTable, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                    .addContainerGap(691, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4)))
        );

        jLabel4.setFont(new java.awt.Font("Alexandria", 1, 24)); // NOI18N
        jLabel4.setText("Assignments");

        English_btn.setBackground(new java.awt.Color(10, 95, 111));
        English_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        English_btn.setForeground(new java.awt.Color(255, 255, 255));
        English_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/icons8-assignment-50 1.png"))); // NOI18N
        English_btn.setText("Diploma in English");
        English_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                English_btnActionPerformed(evt);
            }
        });

        IT_btn.setBackground(new java.awt.Color(10, 95, 111));
        IT_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IT_btn.setForeground(new java.awt.Color(255, 255, 255));
        IT_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/icons8-assignment-50 1.png"))); // NOI18N
        IT_btn.setText("Diploma in IT");
        IT_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT_btnActionPerformed(evt);
            }
        });

        HND_btn.setBackground(new java.awt.Color(10, 95, 111));
        HND_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HND_btn.setForeground(new java.awt.Color(255, 255, 255));
        HND_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/icons8-assignment-50 1.png"))); // NOI18N
        HND_btn.setText("HND in Computing");
        HND_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HND_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/pdf1.png"))); // NOI18N
        jLabel5.setText("IT Assignment 1                                                10/ 10 / 2025");

        jLabel6.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/pdf1.png"))); // NOI18N
        jLabel6.setText("IT Assignment 2                                                10/ 10 / 2025");

        jLabel7.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/pdf1.png"))); // NOI18N
        jLabel7.setText("IT Assignment 3                                                 10/ 10 / 2025");

        jLabel8.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/pdf1.png"))); // NOI18N
        jLabel8.setText("IT Assignment 6                                                  10/ 10 / 2025");

        jLabel9.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/pdf1.png"))); // NOI18N
        jLabel9.setText("IT Assignment 5                                                 10/ 10 / 2025");

        jLabel10.setFont(new java.awt.Font("Alexandria", 0, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/pdf1.png"))); // NOI18N
        jLabel10.setText("IT Assignment 4                                                 10/ 10 / 2025");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("                 Assignment                                                  Deadline");

        upload_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/upload1.png"))); // NOI18N
        upload_btn.setText("Upload");
        upload_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_btnActionPerformed(evt);
            }
        });

        upload_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/upload1.png"))); // NOI18N
        upload_btn1.setText("Upload");
        upload_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_btn1ActionPerformed(evt);
            }
        });

        upload_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/upload1.png"))); // NOI18N
        upload_btn2.setText("Upload");
        upload_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_btn2ActionPerformed(evt);
            }
        });

        upload_btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/upload1.png"))); // NOI18N
        upload_btn3.setText("Upload");
        upload_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_btn3ActionPerformed(evt);
            }
        });

        upload_btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/upload1.png"))); // NOI18N
        upload_btn4.setText("Upload");
        upload_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_btn4ActionPerformed(evt);
            }
        });

        upload_btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/upload1.png"))); // NOI18N
        upload_btn5.setText("Upload");
        upload_btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_btn5ActionPerformed(evt);
            }
        });

        open_btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/folder1.png"))); // NOI18N
        open_btn4.setText("Open");
        open_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_btn4ActionPerformed(evt);
            }
        });

        open_btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/folder1.png"))); // NOI18N
        open_btn5.setText("Open");
        open_btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_btn5ActionPerformed(evt);
            }
        });

        Delete_btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/delete1.png"))); // NOI18N
        Delete_btn5.setText("Delete");
        Delete_btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btn5ActionPerformed(evt);
            }
        });

        Delete_btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/delete1.png"))); // NOI18N
        Delete_btn4.setText("Delete");
        Delete_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btn4ActionPerformed(evt);
            }
        });

        Delete_btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/delete1.png"))); // NOI18N
        Delete_btn3.setText("Delete");
        Delete_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btn3ActionPerformed(evt);
            }
        });

        Delete_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/delete1.png"))); // NOI18N
        Delete_btn2.setText("Delete");
        Delete_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btn2ActionPerformed(evt);
            }
        });

        Delete_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/delete1.png"))); // NOI18N
        Delete_btn1.setText("Delete");
        Delete_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btn1ActionPerformed(evt);
            }
        });

        open_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/folder1.png"))); // NOI18N
        open_btn1.setText("Open");
        open_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_btn1ActionPerformed(evt);
            }
        });

        open_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/folder1.png"))); // NOI18N
        open_btn2.setText("Open");
        open_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_btn2ActionPerformed(evt);
            }
        });

        open_btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/folder1.png"))); // NOI18N
        open_btn3.setText("Open");
        open_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_btn3ActionPerformed(evt);
            }
        });

        open_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/folder1.png"))); // NOI18N
        open_btn.setText("Open");
        open_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_btnActionPerformed(evt);
            }
        });

        Delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learning_management_system/assets/delete1.png"))); // NOI18N
        Delete_btn.setText("Delete");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(English_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(IT_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(HND_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(upload_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(open_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete_btn)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(upload_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(open_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete_btn1)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(upload_btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(open_btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete_btn2)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(upload_btn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(open_btn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete_btn3)
                        .addGap(5, 5, 5))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(upload_btn4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(open_btn4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Delete_btn4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(upload_btn5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(open_btn5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Delete_btn5)))))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(English_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HND_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IT_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(upload_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(open_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(upload_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(open_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(upload_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(open_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(upload_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(open_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(upload_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(open_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Delete_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(upload_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(open_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Delete_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HND_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HND_btnActionPerformed
        // TODO add your handling code here:
        assignments_app3 ass3 = new assignments_app3();
        ass3.setVisible(true);
        dispose();
    }//GEN-LAST:event_HND_btnActionPerformed

    private void IT_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT_btnActionPerformed
        // TODO add your handling code here:
        assignments_app2 ass2 = new assignments_app2();
        ass2.setVisible(true);
        dispose();
    }//GEN-LAST:event_IT_btnActionPerformed

    private void English_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_English_btnActionPerformed
        // TODO add your handling code here:
        assignments_app ass = new assignments_app();
        ass.setVisible(true);
        dispose();
    }//GEN-LAST:event_English_btnActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to log out?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            loginApllication login = new loginApllication();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to exit the application?",
            "Confirm Exit",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            System.exit(0); // Close the application
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void courcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courcesActionPerformed
        // TODO add your handling code here:
        cources cources = new cources();
        cources.setVisible(true);
        dispose();
    }//GEN-LAST:event_courcesActionPerformed

    private void Home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_btnActionPerformed
        // TODO add your handling code here:
        dashboard dash = new dashboard();
        dash.setVisible(true);
        dispose();
    }//GEN-LAST:event_Home_btnActionPerformed

    private void Assignments_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assignments_btnActionPerformed
        // TODO add your handling code here:
        assignments_app ass = new assignments_app();
        ass.setVisible(true);
        dispose();
    }//GEN-LAST:event_Assignments_btnActionPerformed

    private void upload_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_btnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files", "pdf");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(null, "Selected file: " + selectedFile.getAbsolutePath());

            File folder = new File("assignments");
            if (!folder.exists()) {
                folder.mkdirs(); // Create folder if it doesn't exist
            }

            File destination = new File(folder, selectedFile.getName());

            try {Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
                uploadedAssignment3File = destination;  // 💡 Save uploaded file path
                JOptionPane.showMessageDialog(null, "File uploaded successfully!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "File upload failed: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "File selection cancelled.");
        }
    }//GEN-LAST:event_upload_btnActionPerformed

    private void upload_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_btn1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files", "pdf");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(null, "Selected file: " + selectedFile.getAbsolutePath());

            File folder = new File("assignments");
            if (!folder.exists()) {
                folder.mkdirs(); // Create folder if it doesn't exist
            }

            File destination = new File(folder, selectedFile.getName());

            try {Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
                uploadedAssignment3File = destination;  // 💡 Save uploaded file path
                JOptionPane.showMessageDialog(null, "File uploaded successfully!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "File upload failed: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "File selection cancelled.");
        }
    }//GEN-LAST:event_upload_btn1ActionPerformed

    private void upload_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_btn2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files", "pdf");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(null, "Selected file: " + selectedFile.getAbsolutePath());

            File folder = new File("assignments");
            if (!folder.exists()) {
                folder.mkdirs(); // Create folder if it doesn't exist
            }

            File destination = new File(folder, selectedFile.getName());

            try {Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
                uploadedAssignment3File = destination;  // 💡 Save uploaded file path
                JOptionPane.showMessageDialog(null, "File uploaded successfully!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "File upload failed: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "File selection cancelled.");
        }
    }//GEN-LAST:event_upload_btn2ActionPerformed

    private void upload_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_btn3ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files", "pdf");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(null, "Selected file: " + selectedFile.getAbsolutePath());

            File folder = new File("assignments");
            if (!folder.exists()) {
                folder.mkdirs(); // Create folder if it doesn't exist
            }

            File destination = new File(folder, selectedFile.getName());

            try {Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
                uploadedAssignment3File = destination;  // 💡 Save uploaded file path
                JOptionPane.showMessageDialog(null, "File uploaded successfully!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "File upload failed: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "File selection cancelled.");
        }
    }//GEN-LAST:event_upload_btn3ActionPerformed

    private void upload_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_btn4ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files", "pdf");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(null, "Selected file: " + selectedFile.getAbsolutePath());

            File folder = new File("assignments");
            if (!folder.exists()) {
                folder.mkdirs(); // Create folder if it doesn't exist
            }

            File destination = new File(folder, selectedFile.getName());

            try {Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
                uploadedAssignment3File = destination;  // 💡 Save uploaded file path
                JOptionPane.showMessageDialog(null, "File uploaded successfully!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "File upload failed: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "File selection cancelled.");
        }
    }//GEN-LAST:event_upload_btn4ActionPerformed

    private void upload_btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_btn5ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files", "pdf");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(null, "Selected file: " + selectedFile.getAbsolutePath());

            File folder = new File("assignments");
            if (!folder.exists()) {
                folder.mkdirs(); // Create folder if it doesn't exist
            }

            File destination = new File(folder, selectedFile.getName());

            try {Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
                uploadedAssignment3File = destination;  // 💡 Save uploaded file path
                JOptionPane.showMessageDialog(null, "File uploaded successfully!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "File upload failed: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "File selection cancelled.");
        }
    }//GEN-LAST:event_upload_btn5ActionPerformed

    private void open_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_btn4ActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(uploadedAssignment3File);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Cannot open file: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Desktop is not supported on this system.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to open.");
        }
    }//GEN-LAST:event_open_btn4ActionPerformed

    private void open_btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_btn5ActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(uploadedAssignment3File);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Cannot open file: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Desktop is not supported on this system.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to open.");
        }
    }//GEN-LAST:event_open_btn5ActionPerformed

    private void Delete_btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btn5ActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete the uploaded file?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (uploadedAssignment3File.delete()) {
                    JOptionPane.showMessageDialog(null, "File deleted successfully!");
                    uploadedAssignment3File = null; // Clear the reference
                } else {
                    JOptionPane.showMessageDialog(null, "File could not be deleted.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to delete.");
        }
    }//GEN-LAST:event_Delete_btn5ActionPerformed

    private void Delete_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btn4ActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete the uploaded file?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (uploadedAssignment3File.delete()) {
                    JOptionPane.showMessageDialog(null, "File deleted successfully!");
                    uploadedAssignment3File = null; // Clear the reference
                } else {
                    JOptionPane.showMessageDialog(null, "File could not be deleted.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to delete.");
        }
    }//GEN-LAST:event_Delete_btn4ActionPerformed

    private void Delete_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btn3ActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete the uploaded file?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (uploadedAssignment3File.delete()) {
                    JOptionPane.showMessageDialog(null, "File deleted successfully!");
                    uploadedAssignment3File = null; // Clear the reference
                } else {
                    JOptionPane.showMessageDialog(null, "File could not be deleted.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to delete.");
        }
    }//GEN-LAST:event_Delete_btn3ActionPerformed

    private void Delete_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btn2ActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete the uploaded file?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (uploadedAssignment3File.delete()) {
                    JOptionPane.showMessageDialog(null, "File deleted successfully!");
                    uploadedAssignment3File = null; // Clear the reference
                } else {
                    JOptionPane.showMessageDialog(null, "File could not be deleted.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to delete.");
        }
    }//GEN-LAST:event_Delete_btn2ActionPerformed

    private void Delete_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btn1ActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete the uploaded file?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (uploadedAssignment3File.delete()) {
                    JOptionPane.showMessageDialog(null, "File deleted successfully!");
                    uploadedAssignment3File = null; // Clear the reference
                } else {
                    JOptionPane.showMessageDialog(null, "File could not be deleted.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to delete.");
        }
    }//GEN-LAST:event_Delete_btn1ActionPerformed

    private void open_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_btn1ActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(uploadedAssignment3File);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Cannot open file: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Desktop is not supported on this system.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to open.");
        }
    }//GEN-LAST:event_open_btn1ActionPerformed

    private void open_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_btn2ActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(uploadedAssignment3File);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Cannot open file: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Desktop is not supported on this system.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to open.");
        }
    }//GEN-LAST:event_open_btn2ActionPerformed

    private void open_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_btn3ActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(uploadedAssignment3File);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Cannot open file: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Desktop is not supported on this system.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to open.");
        }
    }//GEN-LAST:event_open_btn3ActionPerformed

    private void open_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_btnActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(uploadedAssignment3File);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Cannot open file: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Desktop is not supported on this system.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to open.");
        }
    }//GEN-LAST:event_open_btnActionPerformed

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        // TODO add your handling code here:
        if (uploadedAssignment3File != null && uploadedAssignment3File.exists()) {
            int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete the uploaded file?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (uploadedAssignment3File.delete()) {
                    JOptionPane.showMessageDialog(null, "File deleted successfully!");
                    uploadedAssignment3File = null; // Clear the reference
                } else {
                    JOptionPane.showMessageDialog(null, "File could not be deleted.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No uploaded file to delete.");
        }
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void TTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTableActionPerformed
        // TODO add your handling code here:
        ttable table = new ttable();
        table.setVisible(true);
        dispose();
    }//GEN-LAST:event_TTableActionPerformed
    
   
    
    private File uploadedAssignment3File = null;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assignments_app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assignments_app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assignments_app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assignments_app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assignments_app2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assignments_btn;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JButton Delete_btn1;
    private javax.swing.JButton Delete_btn2;
    private javax.swing.JButton Delete_btn3;
    private javax.swing.JButton Delete_btn4;
    private javax.swing.JButton Delete_btn5;
    private javax.swing.JButton English_btn;
    private javax.swing.JButton HND_btn;
    private javax.swing.JButton Home_btn;
    private javax.swing.JButton IT_btn;
    private javax.swing.JButton TTable;
    private javax.swing.JButton cources;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton logout;
    private javax.swing.JButton open_btn;
    private javax.swing.JButton open_btn1;
    private javax.swing.JButton open_btn2;
    private javax.swing.JButton open_btn3;
    private javax.swing.JButton open_btn4;
    private javax.swing.JButton open_btn5;
    private Panel_redondo.PanelRound panelRound1;
    private javax.swing.JButton upload_btn;
    private javax.swing.JButton upload_btn1;
    private javax.swing.JButton upload_btn2;
    private javax.swing.JButton upload_btn3;
    private javax.swing.JButton upload_btn4;
    private javax.swing.JButton upload_btn5;
    // End of variables declaration//GEN-END:variables
}
